# Numpy ndarry对象
NumPy定义了一个n维数组对象，简称ndarry对象，他是一个**一系列相同类型**的元素组成的数组集合。数组中的每个元素都占用相同大小的内存块。
ndarry对象采用了数组的**索引机制**，将数组的每个元素**映射**到内存块上，并按照一定的布局对内存块进行排序（行或者列）

## Numpy创建数组
| 序号 | 参数   | 描述说明                                                     |
| ---- | ------ | ------------------------------------------------------------ |
| 1    | object | 表示一个数组序列                                             |
| 2    | dtype  | 可选参数，通过它更改数组的数据类型                           |
| 3    | cpoy   | 可选参数，当数据源是ndarray时表示数组能否被复制，默认为True  |
| 4    | order  | 可选参数，以哪一种内存布局创建数组，有三个可选值，分别为C(行序列)，F(列序列)以及A(默认) |
| 5    | ndmin  | 可选参数，用于指定数组的维度                                 |
| 6    | subok  | 可选参数，类型是bool值，默认为False。为True，使用object的内部数据类型；False：使用object数组的数据类型 |

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

In [ ]:
type(np.array([1,2,3,4,5]))

In [ ]:
np.array((1,2,3,4,5))

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array(a)
b

In [ ]:
# 迭代对象
np.array(range(10))

In [ ]:
# 生成器
np.array([i**2 for i in range(10)])

### 练习1
创建一个10以内的偶数数组

In [ ]:
a = []
for i in range(10):
    if i%2 == 0:
        a.append(i)
np.array(a)

In [ ]:
# 生成式
np.array([i for i in range(10) if i%2 == 0])

In [ ]:
# 列表中元素的类型不同
np.array([1,2,3,4.5,'5'])

In [ ]:
ar1 = np.array(range(10)) # 整型
ar1

In [ ]:
ar2 = np.array([1,2,3.14,4,5]) # 浮点型
ar2

In [ ]:
ar3 = np.array([[1,2,3],('a','b','c')]) # 二维数组
ar3

In [ ]:
# 嵌套序列的数量不一样会怎么样,会报错
ar4 = np.array([[1,2,3],('a','b','c','d')])
ar4

In [ ]:
# 嵌套序列的数量不一样会怎么样，会报错
ar4 = np.array([[1,2,3],[1,2,3,4]])
ar4

### 1.设置dtype参数，默认为自动识别

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
# 设置数组元素类型
has_dtype_a = np.array([1,2,3,4,5],dtype='float')
has_dtype_a

### 若将浮点型设置为整形，结果会怎么样

In [ ]:
np.array([1.1,2.2,3.4,4.6,5.8],dtype='int')

### 2.设置copy参数，默认为True

In [ ]:
a = np.array([1,2,3,4,5])
# 定义b，复制a
b = np.array(a)
# 输出a和b的id
print('a:',a,'b',b)
print('a:',id(a),'b:',id(b))
print('上述代码可以看出a和b的内存地址')

In [ ]:
# 当我们修改b元素的时候，a不会发生改变
b[0] = 10
print('a:',a,'b:',b)


In [ ]:
a = np.array([1,2,3,4,5])
# 直接等于，是试图操作，相当于列表的引用赋值
b =a
# 输出a和b的id
print('a:',a,'b',b)
print('a:',id(a),'b:',id(b))
print('上述代码可以看出a和b的内存地址')

In [ ]:
# 此时若对b进行操作，那么由于a和b是同一个内存地址，那么a也会发生变化
b[0] = 10
print('a:',a,'b:',b)

In [ ]:
a = np.array([1,2,3,4,5])
# 定义b，当设置copy参数为False的时候，不会创建副本
# 两个变量指向一个内存地址，没有创建新的对象
b = np.array(a,copy=False)
print('a:',a,'b',b)
print('a:',id(a),'b:',id(b))
print('上述代码可以看出a和b的内存地址')
# 此时若对b进行操作，那么由于a和b是同一个内存地址，那么a也会发生变化
b[0] = 10
print('a:',a,'b:',b)

### 3.ndmin用于指定数组的维度

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

a = np.array([1,2,3,4,5],ndmin=2)
print(a)

### 4.subok参数，类型为bool值，默认为False。为True，使用object的内部数据类型。False：使用数组的类型

In [ ]:
# # 创建一个矩阵
# a = np.asmatrix([1,2,3,4])  # 貌似新版本的numpy取消类.mat方法，这个地方存疑
# # 输出矩阵的类型
# print(type(a))
# # 既要复制一份副本又要保持原类型
# at = np.asmatrix(a)
# af = np.asmatrix(a)

## 练习
- 1.创建一个一维数组
- 2.创建一个二维数组
- 3.创建嵌套序列数目不一样的数组，查看结果
- 4.测试数组a，若将数组直接赋值给b，修改b中的一个元素，查看a是否变化
- 5.紧接着测试4.若不想让b变化影响a，如何实现

In [ ]:
a1 = np.array([1,2,3,4,5])
a1

In [ ]:
a2 = np.array([[1,2,3,4,5]])
a2
print(type(a1))

In [ ]:
a3 = np.array([[1,2,3,4,5],[1,2,3,4]],dtype=object)
a3
print(type(a3))

In [47]:
a = np.array([1,2,3,4,5])
b = a
b[2] = 10
print(a)
print(b)

[ 1  2 10  4  5]
[ 1  2 10  4  5]


In [48]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[2] = 10
print(a)
print(b)

[1 2 3 4 5]
[ 1  2 10  4  5]
